apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::299409672922:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13C4N6BQNLPBA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::299409672922:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-08T10:19:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1503"
  uid: 1fc25091-f8e5-4905-98b9-8767c60c8a62
